### PR TITLE
feat: add TypeScript types

### LINKED ISSUE #7: TypeScript types?
Can you publish an `index.d.ts` for this library, please?

### PR DESCRIPTION
**Pull request by Pustur**
Added types for TypeScript users.

Example usage:

```ts
import fastFolderSize = require('fast-folder-size');

fastFolderSize('.', (err, bytes) => {
  if (err) console.log(err);
  else console.log(bytes);
});
```

Closes #7

### CODE REVIEW

**Review by simoneb — COMMENTED** [review]
Thanks for the PR. I would appreciate if you could add automated tests with TSD: https://github.com/SamVerschueren/tsd.

You can inspire from the way it's used here, for example: https://github.com/nearform/sql/blob/master/SQL.test-d.ts

**Comment by Pustur** [comment]
@simoneb I hope I did it correctly, please check the new changes 🙂

**Review by simoneb — APPROVED** [review]

**Comment by simoneb** [comment]
> PS: Unrelated, but I would suggets to remove `.npmignore` and instead whitelist the files that should be uploaded to npm using the `files` property inside `package.json`.

Why?

**Comment by Pustur** [comment]
@simoneb If you run `npm pack --dry-run` in the project folder you'll see that there are a bunch of files that are not really required by the end user. You could either blacklist them all in `.npmignore` but often it's simpler to just whitelist the ones you want.

**Comment by simoneb** [comment]
They cause no harm if they're there.

**Comment by Pustur** [comment]
You're right, maybe I'm a bit too perfectionist in these small things.

Thanks for merging the PR anyway, have a nice evening 🙂

**Pull request merged**
