### PR TITLE
Improve DU download

### PR DESCRIPTION
**Pull request by mubaidr**
This pull request adds

- proxy support for user environment proxy configuration. 
- checks if `exe` already downloaded then skip download

### CODE REVIEW

**Comment by simoneb** [comment]
I'm not sure why you closed this, I think the request makes sense, I just wanted to come up with a more generic way to handle this

**Comment by mubaidr** [comment]
Please share idea, I will open new pull request.

**Comment by simoneb** [comment]
If your requirement is to be able to load the file from the file system, can't we just handle it in the existing environment variable and, if it's a url, download it, otherwise copy the file from the file system to the expected location (or even just use it as-is)?

**Comment by simoneb** [comment]
Okay fair enough. I'm happy to get a PR which does either or both. When possible, please consider including unit tests to check that this works

**Pull request closed without merging**
